[project]
name = "arronwh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.135.3",
    "fitz>=0.0.1.dev2",
    "httpx>=0.28.1",
    "langchain>=1.2.15",
    "langchain-openai>=1.1.12",
    "langchain-text-splitters>=1.1.2",
    "openai>=2.30.0",
    "pandas>=3.0.2",
    "pymongo>=4.16.0",
    "pymupdf>=1.27.2.3",
    "python-docx>=1.2.0",
    "requests>=2.33.1",
    "sentence-transformers>=5.4.1",
    "streamlit>=1.44.0",
]
